enum StreamActionType {

	STREAM_INIT,
	STREAM_START,

	STREAM_PAGE_ACTION,
	STREAM_PAGE_ACTIONS,
	STREAM_PAGE_CREATED,
	STREAM_PAGE_DELETED,
	STREAM_PAGE_SELECTED,

	STREAM_DOCUMENT_CREATED,
	STREAM_DOCUMENT_CLOSED,
	STREAM_DOCUMENT_SELECTED,

	STREAM_SPEECH_PUBLISHED
}

export { StreamActionType };