version: '2.1'
services:
  #
  # janus-gateway
  #
  janus-gateway:
    image: 'canyan/janus-gateway:master'
    container_name: janus-multistream-server
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "10188:8188"
      - "10088:8088"
      - "10089:8089"
      - "10889:8889"
      - "10000:8000"
      - "9088:7088"
      - "9089:7089"
    volumes:
      - "./config/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./config/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.cfg"
      - "./config/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
    restart: always
  angularserver:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: angularlecutreplayer:tag
    ports:
      - "11111:80"