version: '2.1'
services:
  #
  # janus-gateway
  #
  #janus-gateway:
  #  image: 'canyan/janus-gateway:master'
  #  container_name: janus-multistream-server
  #  command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
  #  volumes:
  #    - "./config/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
  #    - "./config/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
  #    - "./config/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
  #    - "./cert.pem:/usr/local/etc/janus/cert.pem"
  #    - "./januskey.pem:/usr/local/etc/janus/januskey.pem"
  #  restart: always
  #  network_mode: "host"
  angularserver:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: angularlecutreplayer:tag
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/mime.types:/etc/nginx/conf/mime.types"
      - "./cert.pem:/etc/ssl/certs/cert.pem"
      - "./key.pem:/etc/ssl/certs/key.pem"
    ports:
      - "11112:443"
      - "11111:80"